name: parts
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - torchaudio=2.1.0
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1
  - tqdm
  - scikit-learn
  - pandas
  - scikit-image
  - tensorboard
  - matplotlib
